repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff linter
        entry: ruff check
        language: system
        types: [python]
      
      - id: ruff-format
        name: ruff formatter
        entry: ruff format
        language: system
        types: [python]
        args: [--check]
      
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        args: ['-v', 'test/']
        pass_filenames: false
        types: [python]
      
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        args: ['.']
        pass_filenames: false
        types: [python]